#!/bin/sh

. ${R}etc/init.d/rc.mc_defaults

# 使用 UDP 与 UE 仿真通信
export PX4_SIM_UDP=1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# geometry (m), FRD body frame: x forward, y right
# KM值是定义了推力（Thrust）与偏航力矩（Yaw Moment）之间的关系
# YAW_TORQUE = KM * THRUST

param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.15
param set-default CA_ROTOR0_PZ 0.08
param set-default CA_ROTOR0_KM 0.0177
#param set-default CA_ROTOR0_KM 0.0189


param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.15
param set-default CA_ROTOR1_PZ 0.08
param set-default CA_ROTOR1_KM 0.0177
# param set-default CA_ROTOR1_KM 0.0189

param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.15
param set-default CA_ROTOR2_PZ 0.08
param set-default CA_ROTOR2_KM -0.0177
# param set-default CA_ROTOR2_KM -0.0189

param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.15
param set-default CA_ROTOR3_PZ 0.08
param set-default CA_ROTOR3_KM -0.0177
#param set-default CA_ROTOR3_KM -0.0189


param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

# 修改水平速度与垂直速度的限制
param set MPC_XY_VEL_MAX 70.0
param set MPC_Z_VEL_MAX_UP 70.0
param set MPC_Z_VEL_MAX_DN 70.0

# 修改角速度的限制
param set MC_ROLLRATE_MAX 720.0
param set MC_PITCHRATE_MAX 720.0
param set MC_YAWRATE_MAX 720.0




# 无人机的最大倾角
param set MPC_TILTMAX_AIR 90.0

# IMU率，这个参数应该是我们实现高频控制的关键
# 取值为100~2000HZ，四旋翼默认为800
param set IMU_GYRO_RATEMAX 800

# 提高 EKF2 积分频率以支持 高 Hz 控制环路,可以在这里进行更改，以实现高HZ的控制频率，比如1000
param set IMU_INTEG_RATE 250
